// apostol_incipits.dart
//
// ⚠⚠ ГЕНЕРИРАН ФАЙЛ — не се редактира на ръка.
// Прави го tools/evangelie_slujebno/scripts/04_gen_incipits_dart.py от
// work/apostol_incipits.csv, който пък се вади от богослужебния Апостол.
//
// БОГОСЛУЖЕБНОТО ОБРЪЩЕНИЕ пред апостолското четиво. Когато четивото се чете
// на служба, отпред застава обръщение, каквото В БИБЛЕЙСКИЯ ТЕКСТ ГО НЯМА.
// Сверено дословно:
//
//     Апостол   „Бра́тие, егда́ прии́де Петр во Антиохи́ю…"
//     bible.db  „[Заⷱ҇ 202] Є҆гда́ же прїи́де пе́тръ…"
//
// ⚠⚠ ОБРЪЩЕНИЯТА СА СЕДЕМ, НЕ ЕДНО — затова се пази ВИДЪТ, а не флаг 0/1.
//
// ⚠ Правилото важи САМО за Апостола. Евангелията имат свои формули („Во время
// оно"), но за тях добавка НЕ се прави (изрично от потребителя).
//
// ⚠ БЕЗ SQLite нарочно: 338 къси реда не заслужават база — четат се направо.

/// Кое обръщение носи зачалото.
enum ApostolIncipit {
  /// „Братя," — посланията към църкви. Най-честото (227 зачала).
  brethren,

  /// „В ония дни," — Деянията.
  thoseDays,

  /// „Чедо Тимотее," / „Чедо Тите," — пастирските послания.
  childTimothy,
  childTitus,

  /// „Възлюбени," — съборните послания.
  beloved,

  /// ⚠⚠ ИЗРИЧНО „НЯМА ОБРЪЩЕНИЕ" — 26 зачала.
  ///
  /// Такива са онези, които започват със самия текст на посланието („Па́вел,
  /// раб Бо́жий…", „Многоча́стне и многообра́зне…"). Записва се ИЗРИЧНО, а не
  /// с липсващ ключ: инак „няма обръщение" и „не знаем" изглеждат еднакво, а
  /// това са различни неща. Липсващ ключ значи ПРОПУСК, който трябва да се
  /// провери в книгата.
  none,
}

/// Обръщението на всеки поддържан език.
///
/// ⚠⚠ ЕЗИК, КОЙТО ГО НЯМА ТУК, НЕ ПОЛУЧАВА НИЩО — и това е нарочно. При
/// гръцкия, ивритa, грузинския и Септуагинтата въпросът дори не стои: там
/// текстът е на изворния език, а обръщението е славянска богослужебна добавка.
/// По-добре нищо, отколкото измислен превод.
///
/// ⚠ Църковнославянските форми са ПРЕПИСАНИ ОТ КНИГАТА, с ударенията. Другите
/// са установените съответствия.
const Map<ApostolIncipit, Map<String, String>> kIncipitText = {
  ApostolIncipit.brethren: {
    'bg': 'Братя,',
    'utfcs': 'Бра́тие,',
    'r': 'Братия,',
    'en-kjv': 'Brethren,',
  },
  ApostolIncipit.thoseDays: {
    'bg': 'В ония дни,',
    'utfcs': 'Во дни о́ны,',
    'r': 'В те дни,',
    'en-kjv': 'In those days,',
  },
  ApostolIncipit.childTimothy: {
    'bg': 'Чедо Тимотее,',
    'utfcs': 'Ча́до Тимофе́е,',
    'r': 'Чадо Тимофей,',
    'en-kjv': 'Son Timothy,',
  },
  ApostolIncipit.childTitus: {
    'bg': 'Чедо Тите,',
    'utfcs': 'Ча́до Ти́те,',
    'r': 'Чадо Тит,',
    'en-kjv': 'Son Titus,',
  },
  ApostolIncipit.beloved: {
    'bg': 'Възлюбени,',
    'utfcs': 'Возлю́бленнии,',
    'r': 'Возлюбленные,',
    'en-kjv': 'Beloved,',
  },
};

/// „книга|зачало" → обръщение. ⚠⚠ ИЗЧЕРПАТЕЛНА: всяко зачало от книгата има
/// ред, а онези без обръщение носят [ApostolIncipit.none]. Липсващ ключ
/// значи, че зачалото изобщо не е намерено в извора — тоест ПРОПУСК.
///
/// ⚠ Ключът носи И КНИГАТА, защото зачалата на Апостола се ЗАСТЪПВАТ в
/// шевовете: 50 и 51 ги има и в Деяния, и в Иаковлевото послание; 68 — в две
/// послания; 302 — в две. Номерът сам не е еднозначен.
const Map<String, ApostolIncipit> kApostolIncipit = {
  '1Cor|110': ApostolIncipit.brethren,
  '1Cor|122': ApostolIncipit.none,
  '1Cor|123': ApostolIncipit.brethren,
  '1Cor|124': ApostolIncipit.brethren,
  '1Cor|125': ApostolIncipit.brethren,
  '1Cor|126': ApostolIncipit.brethren,
  '1Cor|127': ApostolIncipit.brethren,
  '1Cor|128': ApostolIncipit.brethren,
  '1Cor|129': ApostolIncipit.brethren,
  '1Cor|130': ApostolIncipit.brethren,
  '1Cor|131': ApostolIncipit.brethren,
  '1Cor|132': ApostolIncipit.brethren,
  '1Cor|134': ApostolIncipit.brethren,
  '1Cor|135': ApostolIncipit.brethren,
  '1Cor|136': ApostolIncipit.brethren,
  '1Cor|137': ApostolIncipit.brethren,
  '1Cor|138': ApostolIncipit.brethren,
  '1Cor|139': ApostolIncipit.brethren,
  '1Cor|140': ApostolIncipit.brethren,
  '1Cor|141': ApostolIncipit.brethren,
  '1Cor|142': ApostolIncipit.brethren,
  '1Cor|143': ApostolIncipit.brethren,
  '1Cor|144': ApostolIncipit.brethren,
  '1Cor|145': ApostolIncipit.brethren,
  '1Cor|146': ApostolIncipit.brethren,
  '1Cor|147': ApostolIncipit.brethren,
  '1Cor|148': ApostolIncipit.brethren,
  '1Cor|149': ApostolIncipit.brethren,
  '1Cor|150': ApostolIncipit.brethren,
  '1Cor|151': ApostolIncipit.brethren,
  '1Cor|152': ApostolIncipit.brethren,
  '1Cor|153': ApostolIncipit.brethren,
  '1Cor|154': ApostolIncipit.brethren,
  '1Cor|155': ApostolIncipit.brethren,
  '1Cor|156': ApostolIncipit.brethren,
  '1Cor|157': ApostolIncipit.brethren,
  '1Cor|158': ApostolIncipit.brethren,
  '1Cor|159': ApostolIncipit.brethren,
  '1Cor|160': ApostolIncipit.brethren,
  '1Cor|161': ApostolIncipit.brethren,
  '1Cor|162': ApostolIncipit.brethren,
  '1Cor|163': ApostolIncipit.brethren,
  '1Cor|164': ApostolIncipit.brethren,
  '1Cor|165': ApostolIncipit.brethren,
  '1Cor|166': ApostolIncipit.brethren,
  '1Jn|68': ApostolIncipit.none,
  '1Jn|69': ApostolIncipit.beloved,
  '1Jn|70': ApostolIncipit.beloved,
  '1Jn|71': ApostolIncipit.none,
  '1Jn|72': ApostolIncipit.beloved,
  '1Jn|73': ApostolIncipit.beloved,
  '1Jn|74': ApostolIncipit.beloved,
  '1Pet|58': ApostolIncipit.none,
  '1Pet|59': ApostolIncipit.beloved,
  '1Pet|60': ApostolIncipit.beloved,
  '1Pet|61': ApostolIncipit.beloved,
  '1Pet|62': ApostolIncipit.beloved,
  '1Pet|63': ApostolIncipit.brethren,
  '1Thes|262': ApostolIncipit.none,
  '1Thes|263': ApostolIncipit.brethren,
  '1Thes|264': ApostolIncipit.brethren,
  '1Thes|265': ApostolIncipit.brethren,
  '1Thes|266': ApostolIncipit.brethren,
  '1Thes|267': ApostolIncipit.brethren,
  '1Thes|268': ApostolIncipit.brethren,
  '1Thes|269': ApostolIncipit.brethren,
  '1Thes|270': ApostolIncipit.brethren,
  '1Thes|271': ApostolIncipit.brethren,
  '1Thes|272': ApostolIncipit.brethren,
  '1Thes|273': ApostolIncipit.brethren,
  '1Tim|278': ApostolIncipit.none,
  '1Tim|279': ApostolIncipit.childTimothy,
  '1Tim|280': ApostolIncipit.childTimothy,
  '1Tim|281': ApostolIncipit.childTimothy,
  '1Tim|282': ApostolIncipit.childTimothy,
  '1Tim|283': ApostolIncipit.childTimothy,
  '1Tim|284': ApostolIncipit.childTimothy,
  '1Tim|285': ApostolIncipit.childTimothy,
  '1Tim|286': ApostolIncipit.childTimothy,
  '1Tim|287': ApostolIncipit.childTimothy,
  '1Tim|288': ApostolIncipit.childTimothy,
  '1Tim|289': ApostolIncipit.childTimothy,
  '2Cor|167': ApostolIncipit.none,
  '2Cor|168': ApostolIncipit.brethren,
  '2Cor|169': ApostolIncipit.brethren,
  '2Cor|170': ApostolIncipit.brethren,
  '2Cor|171': ApostolIncipit.brethren,
  '2Cor|172': ApostolIncipit.brethren,
  '2Cor|173': ApostolIncipit.brethren,
  '2Cor|174': ApostolIncipit.brethren,
  '2Cor|175': ApostolIncipit.brethren,
  '2Cor|176': ApostolIncipit.brethren,
  '2Cor|177': ApostolIncipit.brethren,
  '2Cor|178': ApostolIncipit.brethren,
  '2Cor|179': ApostolIncipit.brethren,
  '2Cor|180': ApostolIncipit.brethren,
  '2Cor|181': ApostolIncipit.brethren,
  '2Cor|182': ApostolIncipit.brethren,
  '2Cor|183': ApostolIncipit.brethren,
  '2Cor|184': ApostolIncipit.brethren,
  '2Cor|185': ApostolIncipit.brethren,
  '2Cor|186': ApostolIncipit.brethren,
  '2Cor|187': ApostolIncipit.brethren,
  '2Cor|188': ApostolIncipit.brethren,
  '2Cor|189': ApostolIncipit.brethren,
  '2Cor|190': ApostolIncipit.brethren,
  '2Cor|191': ApostolIncipit.brethren,
  '2Cor|192': ApostolIncipit.brethren,
  '2Cor|193': ApostolIncipit.brethren,
  '2Cor|194': ApostolIncipit.brethren,
  '2Cor|195': ApostolIncipit.brethren,
  '2Cor|196': ApostolIncipit.brethren,
  '2Cor|197': ApostolIncipit.brethren,
  '2Jn|75': ApostolIncipit.none,
  '2Pet|64': ApostolIncipit.none,
  '2Pet|65': ApostolIncipit.brethren,
  '2Pet|66': ApostolIncipit.beloved,
  '2Pet|67': ApostolIncipit.beloved,
  '2Pet|68': ApostolIncipit.beloved,
  '2Thes|274': ApostolIncipit.none,
  '2Thes|275': ApostolIncipit.brethren,
  '2Thes|276': ApostolIncipit.brethren,
  '2Thes|277': ApostolIncipit.brethren,
  '2Tim|290': ApostolIncipit.none,
  '2Tim|291': ApostolIncipit.childTimothy,
  '2Tim|292': ApostolIncipit.childTimothy,
  '2Tim|293': ApostolIncipit.childTimothy,
  '2Tim|294': ApostolIncipit.childTimothy,
  '2Tim|295': ApostolIncipit.childTimothy,
  '2Tim|296': ApostolIncipit.childTimothy,
  '2Tim|297': ApostolIncipit.childTimothy,
  '2Tim|298': ApostolIncipit.childTimothy,
  '2Tim|299': ApostolIncipit.childTimothy,
  '3Jn|76': ApostolIncipit.none,
  'Act|1': ApostolIncipit.none,
  'Act|2': ApostolIncipit.thoseDays,
  'Act|3': ApostolIncipit.thoseDays,
  'Act|4': ApostolIncipit.thoseDays,
  'Act|5': ApostolIncipit.thoseDays,
  'Act|6': ApostolIncipit.thoseDays,
  'Act|7': ApostolIncipit.thoseDays,
  'Act|8': ApostolIncipit.thoseDays,
  'Act|9': ApostolIncipit.thoseDays,
  'Act|10': ApostolIncipit.thoseDays,
  'Act|11': ApostolIncipit.thoseDays,
  'Act|12': ApostolIncipit.thoseDays,
  'Act|13': ApostolIncipit.thoseDays,
  'Act|14': ApostolIncipit.thoseDays,
  'Act|15': ApostolIncipit.thoseDays,
  'Act|16': ApostolIncipit.thoseDays,
  'Act|17': ApostolIncipit.thoseDays,
  'Act|18': ApostolIncipit.thoseDays,
  'Act|19': ApostolIncipit.thoseDays,
  'Act|20': ApostolIncipit.thoseDays,
  'Act|21': ApostolIncipit.thoseDays,
  'Act|22': ApostolIncipit.thoseDays,
  'Act|23': ApostolIncipit.thoseDays,
  'Act|24': ApostolIncipit.thoseDays,
  'Act|25': ApostolIncipit.thoseDays,
  'Act|26': ApostolIncipit.thoseDays,
  'Act|27': ApostolIncipit.thoseDays,
  'Act|28': ApostolIncipit.thoseDays,
  'Act|29': ApostolIncipit.thoseDays,
  'Act|30': ApostolIncipit.thoseDays,
  'Act|31': ApostolIncipit.thoseDays,
  'Act|32': ApostolIncipit.thoseDays,
  'Act|33': ApostolIncipit.thoseDays,
  'Act|34': ApostolIncipit.thoseDays,
  'Act|35': ApostolIncipit.thoseDays,
  'Act|36': ApostolIncipit.thoseDays,
  'Act|37': ApostolIncipit.thoseDays,
  'Act|38': ApostolIncipit.thoseDays,
  'Act|39': ApostolIncipit.thoseDays,
  'Act|40': ApostolIncipit.thoseDays,
  'Act|41': ApostolIncipit.thoseDays,
  'Act|42': ApostolIncipit.thoseDays,
  'Act|43': ApostolIncipit.thoseDays,
  'Act|44': ApostolIncipit.thoseDays,
  'Act|45': ApostolIncipit.thoseDays,
  'Act|46': ApostolIncipit.thoseDays,
  'Act|47': ApostolIncipit.thoseDays,
  'Act|48': ApostolIncipit.thoseDays,
  'Act|49': ApostolIncipit.thoseDays,
  'Act|50': ApostolIncipit.thoseDays,
  'Act|51': ApostolIncipit.thoseDays,
  'Col|249': ApostolIncipit.none,
  'Col|250': ApostolIncipit.brethren,
  'Col|251': ApostolIncipit.brethren,
  'Col|252': ApostolIncipit.brethren,
  'Col|253': ApostolIncipit.brethren,
  'Col|254': ApostolIncipit.brethren,
  'Col|255': ApostolIncipit.brethren,
  'Col|256': ApostolIncipit.brethren,
  'Col|257': ApostolIncipit.brethren,
  'Col|258': ApostolIncipit.brethren,
  'Col|259': ApostolIncipit.brethren,
  'Col|260': ApostolIncipit.brethren,
  'Col|261': ApostolIncipit.brethren,
  'Eph|216': ApostolIncipit.none,
  'Eph|217': ApostolIncipit.brethren,
  'Eph|218': ApostolIncipit.brethren,
  'Eph|219': ApostolIncipit.brethren,
  'Eph|220': ApostolIncipit.brethren,
  'Eph|221': ApostolIncipit.brethren,
  'Eph|222': ApostolIncipit.brethren,
  'Eph|223': ApostolIncipit.brethren,
  'Eph|224': ApostolIncipit.brethren,
  'Eph|225': ApostolIncipit.brethren,
  'Eph|226': ApostolIncipit.brethren,
  'Eph|227': ApostolIncipit.brethren,
  'Eph|228': ApostolIncipit.brethren,
  'Eph|229': ApostolIncipit.brethren,
  'Eph|230': ApostolIncipit.brethren,
  'Eph|231': ApostolIncipit.brethren,
  'Eph|232': ApostolIncipit.brethren,
  'Eph|233': ApostolIncipit.brethren,
  'Eph|234': ApostolIncipit.brethren,
  'Gal|198': ApostolIncipit.none,
  'Gal|199': ApostolIncipit.brethren,
  'Gal|200': ApostolIncipit.brethren,
  'Gal|201': ApostolIncipit.brethren,
  'Gal|202': ApostolIncipit.brethren,
  'Gal|203': ApostolIncipit.brethren,
  'Gal|204': ApostolIncipit.brethren,
  'Gal|205': ApostolIncipit.brethren,
  'Gal|207': ApostolIncipit.brethren,
  'Gal|208': ApostolIncipit.brethren,
  'Gal|209': ApostolIncipit.brethren,
  'Gal|210': ApostolIncipit.brethren,
  'Gal|211': ApostolIncipit.brethren,
  'Gal|212': ApostolIncipit.brethren,
  'Gal|213': ApostolIncipit.brethren,
  'Gal|214': ApostolIncipit.brethren,
  'Gal|215': ApostolIncipit.brethren,
  'Hebr|303': ApostolIncipit.none,
  'Hebr|304': ApostolIncipit.none,
  'Hebr|305': ApostolIncipit.brethren,
  'Hebr|306': ApostolIncipit.brethren,
  'Hebr|307': ApostolIncipit.brethren,
  'Hebr|308': ApostolIncipit.brethren,
  'Hebr|309': ApostolIncipit.brethren,
  'Hebr|310': ApostolIncipit.brethren,
  'Hebr|311': ApostolIncipit.brethren,
  'Hebr|312': ApostolIncipit.brethren,
  'Hebr|313': ApostolIncipit.brethren,
  'Hebr|314': ApostolIncipit.brethren,
  'Hebr|315': ApostolIncipit.brethren,
  'Hebr|316': ApostolIncipit.brethren,
  'Hebr|317': ApostolIncipit.brethren,
  'Hebr|318': ApostolIncipit.brethren,
  'Hebr|319': ApostolIncipit.brethren,
  'Hebr|320': ApostolIncipit.brethren,
  'Hebr|321': ApostolIncipit.brethren,
  'Hebr|322': ApostolIncipit.brethren,
  'Hebr|323': ApostolIncipit.brethren,
  'Hebr|324': ApostolIncipit.brethren,
  'Hebr|325': ApostolIncipit.brethren,
  'Hebr|326': ApostolIncipit.brethren,
  'Hebr|327': ApostolIncipit.brethren,
  'Hebr|328': ApostolIncipit.brethren,
  'Hebr|329': ApostolIncipit.brethren,
  'Hebr|330': ApostolIncipit.brethren,
  'Hebr|331': ApostolIncipit.brethren,
  'Hebr|332': ApostolIncipit.brethren,
  'Hebr|333': ApostolIncipit.brethren,
  'Hebr|334': ApostolIncipit.brethren,
  'Hebr|335': ApostolIncipit.brethren,
  'Jac|50': ApostolIncipit.none,
  'Jac|51': ApostolIncipit.brethren,
  'Jac|52': ApostolIncipit.brethren,
  'Jac|53': ApostolIncipit.brethren,
  'Jac|54': ApostolIncipit.brethren,
  'Jac|55': ApostolIncipit.brethren,
  'Jac|56': ApostolIncipit.beloved,
  'Jac|57': ApostolIncipit.brethren,
  'Juda|77': ApostolIncipit.none,
  'Juda|78': ApostolIncipit.none,
  'Phil|235': ApostolIncipit.none,
  'Phil|236': ApostolIncipit.brethren,
  'Phil|237': ApostolIncipit.brethren,
  'Phil|238': ApostolIncipit.brethren,
  'Phil|239': ApostolIncipit.brethren,
  'Phil|240': ApostolIncipit.brethren,
  'Phil|241': ApostolIncipit.brethren,
  'Phil|242': ApostolIncipit.brethren,
  'Phil|243': ApostolIncipit.brethren,
  'Phil|244': ApostolIncipit.brethren,
  'Phil|245': ApostolIncipit.brethren,
  'Phil|246': ApostolIncipit.brethren,
  'Phil|247': ApostolIncipit.brethren,
  'Phil|248': ApostolIncipit.brethren,
  'Phlm|302': ApostolIncipit.none,
  'Rom|79': ApostolIncipit.none,
  'Rom|80': ApostolIncipit.brethren,
  'Rom|81': ApostolIncipit.brethren,
  'Rom|82': ApostolIncipit.brethren,
  'Rom|83': ApostolIncipit.brethren,
  'Rom|84': ApostolIncipit.brethren,
  'Rom|85': ApostolIncipit.brethren,
  'Rom|86': ApostolIncipit.brethren,
  'Rom|87': ApostolIncipit.brethren,
  'Rom|88': ApostolIncipit.brethren,
  'Rom|89': ApostolIncipit.brethren,
  'Rom|90': ApostolIncipit.brethren,
  'Rom|91': ApostolIncipit.brethren,
  'Rom|92': ApostolIncipit.brethren,
  'Rom|93': ApostolIncipit.brethren,
  'Rom|94': ApostolIncipit.brethren,
  'Rom|95': ApostolIncipit.brethren,
  'Rom|96': ApostolIncipit.brethren,
  'Rom|97': ApostolIncipit.brethren,
  'Rom|98': ApostolIncipit.brethren,
  'Rom|99': ApostolIncipit.brethren,
  'Rom|100': ApostolIncipit.brethren,
  'Rom|101': ApostolIncipit.brethren,
  'Rom|102': ApostolIncipit.brethren,
  'Rom|103': ApostolIncipit.brethren,
  'Rom|104': ApostolIncipit.brethren,
  'Rom|105': ApostolIncipit.brethren,
  'Rom|106': ApostolIncipit.brethren,
  'Rom|107': ApostolIncipit.brethren,
  'Rom|108': ApostolIncipit.brethren,
  'Rom|109': ApostolIncipit.brethren,
  'Rom|110': ApostolIncipit.brethren,
  'Rom|111': ApostolIncipit.brethren,
  'Rom|112': ApostolIncipit.brethren,
  'Rom|113': ApostolIncipit.brethren,
  'Rom|114': ApostolIncipit.brethren,
  'Rom|115': ApostolIncipit.brethren,
  'Rom|116': ApostolIncipit.brethren,
  'Rom|117': ApostolIncipit.brethren,
  'Rom|118': ApostolIncipit.brethren,
  'Rom|119': ApostolIncipit.brethren,
  'Rom|120': ApostolIncipit.brethren,
  'Rom|121': ApostolIncipit.brethren,
  'Tit|300': ApostolIncipit.none,
  'Tit|301': ApostolIncipit.childTitus,
  'Tit|302': ApostolIncipit.childTitus,
};

/// Обръщението за (книга, зачало).
///
/// ⚠ Три различни изхода, и трите значат нещо:
///   [ApostolIncipit.none] — зачалото Е в книгата и НЯМА обръщение;
///   `null`                — зачалото изобщо не е намерено, тоест ПРОПУСК;
///   останалите            — самото обръщение.
ApostolIncipit? apostolIncipitFor(String book, int zachalo) =>
    kApostolIncipit['$book|$zachalo'];

/// Готовият текст за език, или `null`, ако не се добавя нищо.
///
/// ⚠ Липсващият език НЕ Е грешка — виж [kIncipitText]: при гръцкия, ивритa и
/// подобните обръщението е славянска добавка и просто не важи.
String? apostolIncipitText(String book, int zachalo, String lang) {
  final kind = apostolIncipitFor(book, zachalo);
  if (kind == null || kind == ApostolIncipit.none) return null;
  return kIncipitText[kind]?[lang];
}
